# Generated by Django 3.1.6 on 2021-02-18 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profiles', '0002_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=60)),
                ('unit_code', models.CharField(max_length=60)),
                ('tutor_contact', models.CharField(max_length=10)),
                ('course_id', models.ManyToManyField(to='Profiles.Course')),
                ('tutor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_createdby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FileField(null=True, upload_to='notes')),
                ('note_title', models.CharField(max_length=30, null=True)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profiles.unit')),
            ],
        ),
    ]
