# Generated by Django 3.1.6 on 2021-02-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_auto_20210224_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='courses_id',
            new_name='course_id',
        ),
    ]
